### ISSUE TITLE
老柴你也开始跳坑了啊233333

### ISSUE THREAD

**Issue by hustanhuang** [FangChai/server-client#1]
果然一个个字符读的。。。

**Comment by FangChai** [comment]
dian的新人任务😂


发送自 Outlook Mobile






On Wed, Dec 23, 2015 at 7:55 PM -0800, "Andrew Huang" <notifications@github.com> wrote:





果然一个个字符读的。。。

---
Reply to this email directly or view it on GitHub:
https://github.com/FangChai/server-client/issues/1

**Comment by FangChai** [comment]
😃
发自我的 iPad
